
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-production
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: production
roleRef:
  kind: ClusterRole
  name: admin  # Usamos el ClusterRole `admin` aquí
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devel-production
  namespace: production
subjects:
  - kind: ServiceAccount
    name: devel
    namespace: production
roleRef:
  kind: ClusterRole
  name: view  # Usamos el ClusterRole `view` para devel en producción
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-production
  namespace: production
subjects:
  - kind: ServiceAccount
    name: prod
    namespace: production
roleRef:
  kind: ClusterRole
  name: edit  # Usamos el ClusterRole `edit` para prod en producción
  apiGroup: rbac.authorization.k8s.io