apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devel
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod
  namespace: default
