FROM python:3.7.17-alpine3.18
RUN apk add --no-cache gcc musl-dev linux-headers libffi-dev && pip install notebook && adduser -D usuario
USER usuario
WORKDIR /home/usuario
EXPOSE 8888
ENTRYPOINT [ "jupyter", "notebook", "--ip=0.0.0.0" ]
